# Generated by Django 5.2.12 on 2026-04-24 19:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['name'], 'verbose_name': 'Account', 'verbose_name_plural': 'Accounts'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-date'], 'verbose_name': 'Transaction', 'verbose_name_plural': 'Transactions'},
        ),
        migrations.AddField(
            model_name='account',
            name='icon',
            field=models.CharField(default='wallet-outline', max_length=50),
        ),
        migrations.AddField(
            model_name='account',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='category',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='account',
            name='color',
            field=models.CharField(default='#22c55e', max_length=7),
        ),
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.CharField(choices=[('BANK', 'Banco'), ('WALLET', 'Carteira'), ('INVESTMENT', 'Investimento'), ('CREDIT', 'Cartão de Crédito')], max_length=15),
        ),
        migrations.AlterField(
            model_name='category',
            name='color',
            field=models.CharField(default='#22c55e', max_length=7),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(default='pricetag-outline', max_length=50),
        ),
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('INCOME', 'Receita'), ('EXPENSE', 'Despesa'), ('BOTH', 'Ambos')], max_length=10),
        ),
    ]
