# Generated by Django 5.2.12 on 2026-04-24 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0002_finance_account_icon_user_category_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='method',
            field=models.CharField(choices=[('CREDIT', 'Crédito'), ('DEBIT', 'Débito'), ('CASH', 'Dinheiro'), ('PIX', 'Pix'), ('INSTALLMENT', 'Parcelado')], max_length=15),
        ),
    ]
