# Generated by Django 5.2.12 on 2026-04-24 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0003_transaction_method_pix'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='balance_applied',
            field=models.BooleanField(default=False),
        ),
    ]
